[project]
name = "zkteco"
version = "1.0.0"
description = "Zkteco device Restful API."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"